import { useState } from 'react';
import { Container } from 'react-bootstrap';
import { motion } from 'framer-motion';
import { useLocation } from 'react-router-dom';
import { useLanguage } from '../../context/LanguageContext';
import { pageSeo } from '../../data/content';
import { kpiDimensions, kpiVision2035, kpiPrinciples, kpiIndicatorCount } from '../../data/generated/kpiFramework';
import SeoHead from '../../components/SeoHead';
import PageHero from '../../components/PageHero';
import './Indicators.css';

const labels = {
  pt: {
    eyebrow: 'Sobre o CP2b',
    subtitle: 'Uma visão simples e transparente de como acompanhamos ciência, inovação e impacto.',
    overviewEyebrow: 'Nosso modelo de acompanhamento',
    overviewTitle: 'Da pesquisa ao impacto real',
    overviewLead: 'Os indicadores ajudam o CP2b a transformar objetivos institucionais em evidências claras. Eles não são uma nota ou um ranking: mostram o que observamos para aprender, decidir e evoluir.',
    dimensionsStat: 'dimensões conectadas', indicatorsStat: 'indicadores observados', horizonStat: 'horizonte estratégico',
    journey: [
      { title: 'Acompanhamos', text: 'Reunimos evidências sobre pesquisa, tecnologia, pessoas e território.', icon: 'bi-eye' },
      { title: 'Compreendemos', text: 'Analisamos avanços, desafios e conexões entre as sete dimensões.', icon: 'bi-diagram-3' },
      { title: 'Evoluímos', text: 'Usamos o aprendizado para orientar decisões e ampliar o impacto do centro.', icon: 'bi-arrow-up-right' },
    ],
    visionEyebrow: 'Onde queremos chegar', visionTitle: 'Visão CP2b 2035', principles: 'Princípios que orientam esse caminho',
    explorerEyebrow: 'Explore o sistema', explorerTitle: 'O que acompanhamos',
    explorerLead: 'Selecione uma dimensão para conhecer os sinais que ajudam o CP2b a entender sua evolução.',
    dimension: 'Dimensão', indicatorsLabel: 'indicadores', observes: 'O que observamos', selectedHint: 'Dimensão selecionada',
  },
  en: {
    eyebrow: 'About CP2b',
    subtitle: 'A simple and transparent view of how we follow science, innovation and impact.',
    overviewEyebrow: 'Our monitoring model', overviewTitle: 'From research to real-world impact',
    overviewLead: 'The indicators help CP2b turn institutional goals into clear evidence. They are not a score or ranking: they show what we observe so that we can learn, decide and evolve.',
    dimensionsStat: 'connected dimensions', indicatorsStat: 'indicators observed', horizonStat: 'strategic horizon',
    journey: [
      { title: 'We observe', text: 'We gather evidence about research, technology, people and territories.', icon: 'bi-eye' },
      { title: 'We understand', text: 'We analyze progress, challenges and connections across seven dimensions.', icon: 'bi-diagram-3' },
      { title: 'We evolve', text: 'We use what we learn to guide decisions and expand the center’s impact.', icon: 'bi-arrow-up-right' },
    ],
    visionEyebrow: 'Where we want to go', visionTitle: 'CP2b Vision 2035', principles: 'Principles guiding this journey',
    explorerEyebrow: 'Explore the framework', explorerTitle: 'What we monitor',
    explorerLead: 'Select a dimension to learn which signals help CP2b understand its progress.',
    dimension: 'Dimension', indicatorsLabel: 'indicators', observes: 'What we observe', selectedHint: 'Selected dimension',
  },
};

const dimensionMeta = {
  cientifica: { icon: 'bi-journal-richtext', pt: 'Qualidade, alcance e continuidade da produção científica.', en: 'Quality, reach and continuity of scientific output.' },
  tecnologica: { icon: 'bi-lightbulb', pt: 'Soluções que avançam da pesquisa para aplicações concretas.', en: 'Solutions advancing from research toward practical applications.' },
  transferencia: { icon: 'bi-briefcase', pt: 'Conexões entre conhecimento, empresas e oportunidades de mercado.', en: 'Connections between knowledge, companies and market opportunities.' },
  ambiental: { icon: 'bi-globe-americas', pt: 'Benefícios ambientais gerados pelas soluções e projetos do centro.', en: 'Environmental benefits generated by the center’s solutions and projects.' },
  social: { icon: 'bi-people', pt: 'Transformações percebidas por comunidades, territórios e políticas públicas.', en: 'Change experienced by communities, territories and public policies.' },
  formacao: { icon: 'bi-mortarboard', pt: 'Formação de pessoas e fortalecimento de novas competências.', en: 'People development and the strengthening of new capabilities.' },
  governanca: { icon: 'bi-building-check', pt: 'Capacidade institucional, transparência e sustentabilidade do centro.', en: 'Institutional capacity, transparency and long-term sustainability.' },
};

const visionIcons = ['bi-compass', 'bi-award', 'bi-rocket-takeoff', 'bi-heart-pulse'];

const Indicators = () => {
  const { language } = useLanguage();
  const { pathname } = useLocation();
  const [selectedDimensionId, setSelectedDimensionId] = useState(kpiDimensions[0].id);
  const seo = pageSeo.indicators[language] || pageSeo.indicators.pt;
  const t = labels[language] || labels.pt;
  const selectedDimension = kpiDimensions.find((dimension) => dimension.id === selectedDimensionId) || kpiDimensions[0];
  const selectedLabel = selectedDimension[language] || selectedDimension.pt;
  const selectedMeta = dimensionMeta[selectedDimension.id];

  return (
    <>
      <SeoHead title={seo.title} description={seo.description} path={pathname} language={language} />
      <PageHero eyebrow={t.eyebrow} title={seo.title} subtitle={t.subtitle} />

      <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
        <Container className="indicators-page py-5">
          <section className="indicators-overview" aria-labelledby="indicators-overview-title">
            <div className="indicators-overview__copy">
              <span className="indicators-eyebrow">{t.overviewEyebrow}</span>
              <h2 id="indicators-overview-title">{t.overviewTitle}</h2>
              <p>{t.overviewLead}</p>
            </div>
            <div className="indicators-stats" aria-label={t.overviewEyebrow}>
              <div className="indicators-stat"><strong>7</strong><span>{t.dimensionsStat}</span></div>
              <div className="indicators-stat"><strong>{kpiIndicatorCount}</strong><span>{t.indicatorsStat}</span></div>
              <div className="indicators-stat indicators-stat--year"><strong>2035</strong><span>{t.horizonStat}</span></div>
            </div>
          </section>

          <section className="indicators-journey" aria-label={t.overviewTitle}>
            {t.journey.map((step, index) => (
              <article className="indicators-journey__step" key={step.title}>
                <div className="indicators-journey__number">0{index + 1}</div>
                <div className="indicators-journey__icon" aria-hidden="true"><i className={`bi ${step.icon}`} /></div>
                <div><h3>{step.title}</h3><p>{step.text}</p></div>
              </article>
            ))}
          </section>

          <section className="indicators-vision" aria-labelledby="indicators-vision-title">
            <div className="indicators-section-heading">
              <span className="indicators-eyebrow">{t.visionEyebrow}</span>
              <h2 id="indicators-vision-title">{t.visionTitle}</h2>
            </div>
            <div className="indicators-vision__grid">
              {kpiVision2035[language].map((item, index) => (
                <article className="indicators-vision__card" key={item}><i className={`bi ${visionIcons[index]}`} aria-hidden="true" /><p>{item}</p></article>
              ))}
            </div>
            <div className="indicators-principles">
              <strong>{t.principles}</strong>
              <div>{kpiPrinciples[language].map((principle) => <span key={principle}>{principle}</span>)}</div>
            </div>
          </section>

          <section className="indicators-explorer" aria-labelledby="indicators-explorer-title">
            <div className="indicators-section-heading indicators-section-heading--centered">
              <span className="indicators-eyebrow">{t.explorerEyebrow}</span>
              <h2 id="indicators-explorer-title">{t.explorerTitle}</h2>
              <p>{t.explorerLead}</p>
            </div>

            <div className="indicators-dimension-nav" aria-label={t.explorerTitle}>
              {kpiDimensions.map((dimension, index) => {
                const dimensionLabel = dimension[language] || dimension.pt;
                const meta = dimensionMeta[dimension.id];
                const active = dimension.id === selectedDimension.id;
                const shortTitle = dimensionLabel.title.replace(/^Dimensão\s+/i, '').replace(/\s+Dimension$/i, '');
                return (
                  <button key={dimension.id} type="button"
                    className={`indicators-dimension-nav__item${active ? ' is-active' : ''}`}
                    style={{ '--dimension-color': dimension.color }} aria-pressed={active}
                    aria-label={`${t.dimension} ${index + 1}: ${dimensionLabel.title}`}
                    onClick={() => setSelectedDimensionId(dimension.id)}>
                    <span className="indicators-dimension-nav__icon" aria-hidden="true"><i className={`bi ${meta.icon}`} /></span>
                    <span className="indicators-dimension-nav__text"><small>{t.dimension} {index + 1}</small><strong>{shortTitle}</strong></span>
                  </button>
                );
              })}
            </div>

            <motion.div key={selectedDimension.id} className="indicators-dimension-panel"
              style={{ '--dimension-color': selectedDimension.color }} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.25 }}>
              <header className="indicators-dimension-panel__header">
                <div className="indicators-dimension-panel__icon" aria-hidden="true"><i className={`bi ${selectedMeta.icon}`} /></div>
                <div><span>{t.selectedHint}</span><h3>{selectedLabel.title}</h3><p>{selectedMeta[language] || selectedMeta.pt}</p></div>
                <div className="indicators-dimension-panel__count"><strong>{selectedDimension.indicators.length}</strong><span>{t.indicatorsLabel}</span></div>
              </header>
              <div className="indicators-list">
                {selectedDimension.indicators.map((indicator) => {
                  const indicatorLabel = indicator[language] || indicator.pt;
                  return (
                    <article className="indicators-list__item" key={indicator.code}>
                      <span className="indicators-list__code">{indicator.code}</span>
                      <div><h4>{indicatorLabel.name}</h4><p><span>{t.observes}:</span> {indicatorLabel.measures}</p></div>
                    </article>
                  );
                })}
              </div>
            </motion.div>
          </section>
        </Container>
      </motion.div>
    </>
  );
};

export default Indicators;
